### ISSUE TITLE
Reproduce test results.

### ISSUE THREAD

**Issue by trinhvg** [PathMMU-Benchmark/PathMMU#3]
Hi, when i use your code to test the Quilt-Llava-v1.5-7b (https://huggingface.co/wisdomik/Quilt-Llava-v1.5-7b), I only get 
{
    "acc": 0.22959183673469388,
    "num_example": 196
}
but your paper has: 47.3
here is my output.json
[output.json](https://github.com/user-attachments/files/17457599/output.json)

Please give us any advice on this.

**Comment by dddavid4real** [comment]
Hello! 

I'm trying to reproduce the results as well. However, during the reproduction process, I met this error:
```
The size of tensor a (108) must match the size of tensor b (3) at non-singleton dimension 1
Error in sample:
...
```

May I ask if you encountered the same error while reproducing Quilt-LLaVA, and if so, how did you resolve it? Thanks!
